# fly.toml app configuration file generated for run-red-water-2151 on 2024-12-22T03:47:04+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'run-red-water-2151'
primary_region = 'nrt'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[http_service]
  min_machines_running = 1
